### ISSUE TITLE
Backend Repository doesnt exist

### ISSUE THREAD

**Issue by jossephus** [livekit-examples/android-livestream#14]
In the readme, there is a link for backend for this project, but the link doesnt work. I would have opend a PR but I couldnt find it anywhere.

**Comment by davidzhao** [comment]
Hi @jossephus, the backend is [here](https://github.com/livekit-examples/livestream)

**Comment by davidzhao** [comment]
we'll update the readme.. apologies for the confusion

**Comment by jossephus** [comment]
Thanks
